/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.smk.pgri.pkg1.jakarta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Atthoriq
 */
public class Petugas_EditKelas extends javax.swing.JFrame {

    /**
     * Creates new form Petugas_EditKelas
     */
    public ResultSet rs;
    Connection CC = new koneksi().connect();
    public Statement stt;
    public Petugas_EditKelas() {
        initComponents();
        readCB();
        getrole();
        getAkses();
        Kelas.setEditable(false);
    }
    public String jrsn;
    public String kls;
    public String idJrsn;
    public int clssNmbr;
    public int IdKelas;
    
     public String sql;
     
    public void readCB(){
       try{
           Statement stat = CC.createStatement();
           sql = "SELECT * FROM jurusan";
           ResultSet rs = stat.executeQuery(sql);
           while(rs.next()){
           String result = rs.getString("Jurusan");
               jurusankombo.addItem(result);
           }
           rs.last();
           int jumlah = rs.getRow();
           rs.first();
       }catch (Exception e){
       
       }
   }
     String role;
    public void getrole(){
        try {
            stt = CC.createStatement();
            rs = stt.executeQuery("SELECT * FROM User WHERE Nis = '"+ UserSession.GetUserId() +"' ");
            if(rs.next()){
                if(rs.getInt("role") > 1){
                    role = "Petugas";
                }else{
                    role = "Admin";
                }
            }
            //jLabel3
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void getAkses(){
        try{
            Statement stat = CC.createStatement();
            String sql = "Select * FROM Akses WHERE NamaAkses = 'Kelas'";
           ResultSet rs = stat.executeQuery(sql);
           if(rs.next()){
                if(rs.getInt(role) < 1){
                    hps.setVisible(false);
           }
        }}
        catch (Exception e){
    }}
    
    public void getPreviousData(){
         try{
           Petugas_DataKelas obj = new Petugas_DataKelas();
           Statement stat = CC.createStatement();
               sql = "SELECT IdKelas FROM kelas Where idJurusan = '"+jurusan.getText()+"' AND TingkatKelas = '"+ Tingkat.getText() +"' AND Kelas = '"+ klaz.getText() +"' LIMIT 1";
              //System.out.println(sql);
               ResultSet rs = stat.executeQuery(sql);
               if(rs.next()){
                  IdKelas = rs.getInt("IdKelas");}
         }catch(Exception e){
           e.printStackTrace();
       
       }
    }
    public void getID(){
        try{
           Statement stat = CC.createStatement();
           sql = "SELECT IdJurusan FROM jurusan Where Jurusan = '"+jrsn+"'";

           ResultSet rs = stat.executeQuery(sql);
           if(rs.next()){
              idJrsn = rs.getString("IdJurusan");
           }
       }catch (Exception e){
           e.printStackTrace();
       
       }
    }
    public void getNumber(){
        try{
               Statement stat = CC.createStatement();
               sql = "SELECT kelas FROM kelas Where idJurusan = '"+idJrsn+"' AND TingkatKelas = '"+ kls +"' ORDER BY `kelas` DESC LIMIT 1";
               
               ResultSet rs = stat.executeQuery(sql);
               if(rs.next()){
                  int tkt = rs.getInt("kelas");
                  clssNmbr = tkt+1;
                  System.out.print(clssNmbr);
               }
           }catch (Exception e){
               e.printStackTrace();

           }
    }
    public void update(){
        try{
           Statement stat = CC.createStatement();
           stat.executeUpdate("UPDATE kelas SET TingkatKelas = '"
                   + kls+"', IdJurusan =  '"
                   +idJrsn+ "', kelas= '"
                   + clssNmbr + "' WHERE IdKelas = '"+ IdKelas +"'");
           JOptionPane.showMessageDialog(null, "Data Kelas Berhasil diUpdate");
       }catch (Exception e){
       e.printStackTrace();
       }
    }
     public void delete(){
        try{
           Statement stat = CC.createStatement();
           stat.executeUpdate("DELETE FROM kelas WHERE `IdKelas`='"+IdKelas+"'");
           JOptionPane.showMessageDialog(null, "Data Kelas Berhasil diHapus");
       }catch (Exception e){
       e.printStackTrace();
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jurusankombo = new javax.swing.JComboBox<>();
        tingkatCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        hps = new javax.swing.JButton();
        Kelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tingkat = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        klaz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Edit kelas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(105, 11, 114, 30);

        jurusankombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jurusankombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Pilih jurusan->" }));
        jurusankombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusankomboActionPerformed(evt);
            }
        });
        jPanel1.add(jurusankombo);
        jurusankombo.setBounds(78, 149, 232, 26);

        tingkatCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tingkatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Pilih Kelas->", "X", "XI", "XII" }));
        tingkatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tingkatComboActionPerformed(evt);
            }
        });
        jPanel1.add(tingkatCombo);
        tingkatCombo.setBounds(78, 82, 232, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jurusan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(35, 126, 49, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tingkat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(35, 59, 46, 17);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 266, 90, 23);

        hps.setText("Hapus");
        hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpsActionPerformed(evt);
            }
        });
        jPanel1.add(hps);
        hps.setBounds(20, 260, 80, 23);

        Kelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Kelas);
        Kelas.setBounds(90, 216, 220, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(35, 193, 32, 17);

        Tingkat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tingkat.setText("XII");
        jPanel1.add(Tingkat);
        Tingkat.setBounds(35, 87, 25, 17);

        jurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jurusan.setText("AKL");
        jPanel1.add(jurusan);
        jurusan.setBounds(35, 154, 40, 17);

        klaz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        klaz.setText("XIIIAKL3");
        jPanel1.add(klaz);
        klaz.setBounds(35, 222, 55, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jurusankomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusankomboActionPerformed
        jrsn =String.valueOf(jurusankombo.getSelectedItem());
        getID();
        getNumber();
        Kelas.setText(kls+idJrsn+clssNmbr);
    }//GEN-LAST:event_jurusankomboActionPerformed

    private void tingkatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tingkatComboActionPerformed
        jurusankombo.setEnabled(true);
      kls = String.valueOf(tingkatCombo.getSelectedItem());
      Kelas.setText(kls);
      if(idJrsn != null){
        getNumber();
        Kelas.setText(kls+idJrsn+clssNmbr);
      } 
    }//GEN-LAST:event_tingkatComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getPreviousData();
        update();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpsActionPerformed
        getPreviousData();
        delete();
        this.dispose();
    }//GEN-LAST:event_hpsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas_EditKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas_EditKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas_EditKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas_EditKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas_EditKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField Kelas;
    public javax.swing.JLabel Tingkat;
    public javax.swing.JButton hps;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jurusan;
    private javax.swing.JComboBox<String> jurusankombo;
    public javax.swing.JLabel klaz;
    private javax.swing.JComboBox<String> tingkatCombo;
    // End of variables declaration//GEN-END:variables
}
