/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.smk.pgri.pkg1.jakarta;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Atthoriq
 */
public class Siswa_Usulan_Buku extends javax.swing.JFrame {
    public ResultSet rs;
    Connection CC = new koneksi().connect();
    public Statement stt;
    /**
     * Creates new form Usulan_Buku
     */
    public Siswa_Usulan_Buku() throws IOException {
        checkLogin();
    }
    int UserId = UserSession.GetUserId();
    public void checkLogin() throws IOException{
        if( UserId <= 0){
             this.dispose();
             Login obj = new Login();
             obj.setVisible(true);
             JOptionPane.showMessageDialog(null, "Harap Login Terlebih Dahulu");
             
        }else{
            initComponents();
        }
    }
    /**
         stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Judul,Penerbit,Penulis,TahunTerbit,Status) VALUES('"+ UserId + "','" 
            + jBuku.getText() + "','"
            + penBuku.getText() + "','"
            + pBuku.getText() + "','"
            + ttBuku.getText()+ "','1')");
            JOptionPane.showMessageDialog(null, "Permintaan Dibuat, Terima Kasih Telah memberi Masukan");
     
     */
    public void insert(){
        try{
            stt = CC.createStatement();
            if(jBuku.getText().isEmpty() && penBuku.getText().isEmpty() && pBuku.getText().isEmpty() ){
                    JOptionPane.showMessageDialog(null, "Mohon masukan data dengan Benar");
            } else if(jBuku.getText().isEmpty()){
                if(pBuku.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Mohon Masukan Data Penulis Atau Judul ");
                }else if(penBuku.getText().isEmpty()){
                    stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Penulis,TahunTerbit,Status) VALUES('"+ UserId + "','" 
                    + pBuku.getText() + "','"
                    + ttBuku.getText()+ "','1')");
                }else{
                    stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Penerbit,Penulis,TahunTerbit,Status) VALUES('"+ UserId + "','"
                    + penBuku.getText() + "','"
                    + pBuku.getText() + "','"
                    + ttBuku.getText()+ "','1')");
                }
            }else if(penBuku.getText().isEmpty()){
                if(pBuku.getText().isEmpty()){
                    stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Judul,TahunTerbit,Status) VALUES('"+ UserId + "','" 
                    + jBuku.getText() + "','"
                    + ttBuku.getText()+ "','1')");
                }else{
                    stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Judul,Penulis,TahunTerbit,Status) VALUES('"+ UserId + "','" 
                    + jBuku.getText() + "','"
                    + pBuku.getText() + "','"
                    + ttBuku.getText()+ "','1')");
                }
            }else if(pBuku.getText().isEmpty()){
                    stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Judul,Penerbit,TahunTerbit,Status) VALUES('"+ UserId + "','" 
                    + jBuku.getText() + "','"
                    + penBuku.getText() + "','"
                    + ttBuku.getText()+ "','1')");
            }else{
                stt.executeUpdate("INSERT INTO UsulanBuku(Nis,Judul,Penerbit,Penulis,TahunTerbit,Status) VALUES('"+ UserId + "','" 
                + jBuku.getText() + "','"
                + penBuku.getText() + "','"
                + pBuku.getText() + "','"
                + ttBuku.getText()+ "','1')");
                
            }
            JOptionPane.showMessageDialog(null, "Permintaan Dibuat, Terima Kasih Telah memberi Masukan");
                    
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jBuku = new javax.swing.JTextField();
        pBuku = new javax.swing.JTextField();
        penBuku = new javax.swing.JTextField();
        ttBuku = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 238), 1, true));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Judul Buku");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Penulis");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Penerbit");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Tahun Terbit");

        jBuku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBuku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pBuku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pBuku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBukujTextField2ActionPerformed(evt);
            }
        });

        penBuku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        penBuku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        penBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penBukujTextField3ActionPerformed(evt);
            }
        });

        ttBuku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ttBuku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ttBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ttBukuKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Form Usulan Buku");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(pBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(penBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(ttBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel30))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(25, 25, 25)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pBukujTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBukujTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pBukujTextField2ActionPerformed

    private void penBukujTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penBukujTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penBukujTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert();
        jBuku.setText(null);
        pBuku.setText(null);
        penBuku.setText(null);
        ttBuku.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttBukuKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         insert();
            jBuku.setText(null);
            pBuku.setText(null);
            penBuku.setText(null);
            ttBuku.setText(null);
            this.dispose();
         }        // TODO add your handling code here:
    }//GEN-LAST:event_ttBukuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa_Usulan_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa_Usulan_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa_Usulan_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa_Usulan_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Siswa_Usulan_Buku().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Siswa_Usulan_Buku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField pBuku;
    private javax.swing.JTextField penBuku;
    private javax.swing.JTextField ttBuku;
    // End of variables declaration//GEN-END:variables
}
